### PR TITLE
Fetch SFML scancode branch when building

### PR DESCRIPTION
**Pull request by JonnyPtn**

### CODE REVIEW

**Comment by kimci86** [comment]
For what it's worth, that change would not suit my workflow. I usually have additional commits to test that I do in my local clone of SFML. That being said, this change would not stop me from building the project as I would just edit the CMakeLists.txt locally.

As it makes building the project simpler for testers, that can be a nice thing.
`.github/workflows/ci.yml` should be updated if we make this change.

**Comment by JonnyPtn** [comment]
Yeah good shout on CI I’ll do that.

Don’t mind putting it behind a `BUILD_SFML` option if that suits?

**Comment by kimci86** [comment]
I was thinking maybe `FetchContent_MakeAvailable`'s option `FIND_PACKAGE_ARGS` added in CMake 3.24 would be a solution, but there is a risk that testers have SFML installed, possibly a version without scancodes, that `find_package` would pick. That might add confusion.

So, adding an option as you suggest seems to be a nice solution to suit everyone.

**Comment by JonnyPtn** [comment]
Updated this to put it behind an option - will default to existing behaviour (find_package)

**Review by eXpl0it3r — APPROVED** [review]

**Pull request merged**
